// apps/server/src/services/venueService.js
// ─────────────────────────────────────────────────────────────────────────────
// Multi-Tenant Venue Provisioning Service
// Handles the full lifecycle of onboarding a new cafe client:
//   1. Create Venue record (tenant root)
//   2. Seed CafeConfig with per-venue white-label settings
//   3. Create Owner user account
//   4. Return provisioning summary for the superadmin
// ─────────────────────────────────────────────────────────────────────────────
import prisma from '../lib/prisma.js';
import bcrypt from 'bcryptjs';
import crypto from 'crypto';

// ─── Default Config Template ─────────────────────────────────────────────────
// Sensible defaults for an Ethiopian cafe. All can be overridden at onboarding.
const DEFAULT_CONFIG = {
  primaryColor:        '#D49E4A',
  secondaryColor:      '#1C1209',
  currency:            'ETB',
  currencySymbol:      'ብር',
  locale:              'am-ET',
  timezone:            'Africa/Addis_Ababa',
  enableCash:          true,
  enableTelebirr:      true,
  enableCbeBirr:       true,
  enableEthiopay:      false,
  enableBankTransfer:  false,
  enableEfy:           true,
  receiptHeader:       'Thank you for your visit!',
  receiptFooter:       'Powered by Jan Systems',
  receiptLanguage:     'BOTH',
  taxpayerCategory:    'B',
};

// ─── Provision New Venue ─────────────────────────────────────────────────────
/**
 * Create a new tenant venue with full config and owner account.
 *
 * @param {{
 *   venueName: string,
 *   venueNameAmharic?: string,
 *   slug: string,
 *   plan?: 'TRIAL'|'BASIC'|'PRO'|'ENTERPRISE',
 *   city?: string,
 *   phone?: string,
 *   tin?: string,
 *   ownerName: string,
 *   ownerEmail: string,
 *   ownerPassword?: string,
 *   config?: object
 * }} data
 */
export async function provisionVenue(data) {
  const {
    venueName, venueNameAmharic, slug, plan = 'TRIAL',
    city, phone, tin,
    ownerName, ownerEmail, ownerPassword,
    config: configOverrides = {}
  } = data;

  // Auto-generate a secure temporary password if not supplied
  const password        = ownerPassword || crypto.randomBytes(8).toString('hex');
  const hashedPassword  = await bcrypt.hash(password, 12);
  const autoGeneratedPw = !ownerPassword;

  return await prisma.$transaction(async (tx) => {
    // 1. Check slug uniqueness
    const existing = await tx.venue.findUnique({ where: { slug } });
    if (existing) throw new Error(`Slug "${slug}" is already taken. Choose another.`);

    // 2. Create Venue
    const venue = await tx.venue.create({
      data: {
        name:         venueName,
        slug,
        plan,
        city:         city || 'Addis Ababa',
        phone:        phone || null,
        subscription: plan === 'TRIAL' ? 'TRIAL' : 'ACTIVE',
        subscriptionExpiresAt: plan === 'TRIAL'
          ? new Date(Date.now() + 30 * 24 * 60 * 60 * 1000) // 30-day trial
          : null,
      }
    });

    // 3. Seed CafeConfig with white-label settings
    const mergedConfig = {
      ...DEFAULT_CONFIG,
      ...configOverrides,
      cafeName:         venueName,
      cafeNameAmharic:  venueNameAmharic || venueName,
      tin:              tin || null,
      venueId:          venue.id,
    };

    await tx.cafeConfig.create({ data: mergedConfig });

    // 4. Create Owner user
    const owner = await tx.user.create({
      data: {
        name:     ownerName,
        email:    ownerEmail,
        password: hashedPassword,
        role:     'OWNER',
        venueId:  venue.id,
      }
    });

    return {
      venue: { id: venue.id, name: venue.name, slug: venue.slug, plan: venue.plan },
      owner: { id: owner.id, email: owner.email, name: owner.name },
      credentials: { email: ownerEmail, password: autoGeneratedPw ? password : '(set by admin)' },
      autoGeneratedPw,
      trialExpiresAt: venue.subscriptionExpiresAt,
    };
  });
}

// ─── Get All Venues (SuperAdmin) ─────────────────────────────────────────────
export async function getAllVenues() {
  const venues = await prisma.venue.findMany({
    include: {
      _count: { select: { users: true, orders: true } },
      cafeConfig: { select: { cafeName: true, primaryColor: true, tin: true, locale: true } },
    },
    orderBy: { createdAt: 'desc' }
  });

  // Add revenue summary for each venue
  const venueIds = venues.map(v => v.id);
  const revenueRows = await prisma.order.groupBy({
    by: ['venueId'],
    where: { venueId: { in: venueIds }, status: 'DONE' },
    _sum: { total: true },
    _count: { id: true },
  });

  const revenueMap = {};
  revenueRows.forEach(r => {
    revenueMap[r.venueId] = { totalRevenue: r._sum.total || 0, orderCount: r._count.id };
  });

  return venues.map(v => ({
    ...v,
    totalRevenue: revenueMap[v.id]?.totalRevenue || 0,
    orderCount:   revenueMap[v.id]?.orderCount   || 0,
  }));
}

// ─── Toggle Venue Status ─────────────────────────────────────────────────────
export async function setVenueStatus(venueId, status) {
  // status: 'ACTIVE' | 'SUSPENDED' | 'CANCELLED'
  return await prisma.venue.update({
    where: { id: venueId },
    data:  { subscription: status }
  });
}

// ─── Upgrade Venue Plan ───────────────────────────────────────────────────────
export async function upgradeVenuePlan(venueId, plan) {
  return await prisma.venue.update({
    where: { id: venueId },
    data:  { plan, subscription: 'ACTIVE', subscriptionExpiresAt: null }
  });
}

// ─── Get Platform Revenue Summary (SuperAdmin Dashboard) ─────────────────────
export async function getPlatformSummary() {
  const [venueCount, userCount, orderStats, trialCount] = await Promise.all([
    prisma.venue.count(),
    prisma.user.count(),
    prisma.order.aggregate({ where: { status: 'DONE' }, _sum: { total: true }, _count: { id: true } }),
    prisma.venue.count({ where: { plan: 'TRIAL' } }),
  ]);

  const planBreakdown = await prisma.venue.groupBy({
    by: ['plan'],
    _count: { id: true },
  });

  return {
    venueCount,
    userCount,
    totalOrders:   orderStats._count.id,
    totalRevenue:  orderStats._sum.total || 0,
    trialCount,
    planBreakdown: planBreakdown.map(p => ({ plan: p.plan, count: p._count.id })),
  };
}
